/** Support report categories for POST /reports (backend enum). */
export const REPORT_CATEGORY = {
  TECHNICAL: 'TECHNICAL',
  ACCOUNT: 'ACCOUNT',
  CONTENT: 'CONTENT',
  CHEATING: 'CHEATING',
  OTHER: 'OTHER',
}

export const REPORT_CATEGORY_OPTIONS = [
  REPORT_CATEGORY.TECHNICAL,
  REPORT_CATEGORY.ACCOUNT,
  REPORT_CATEGORY.CONTENT,
  REPORT_CATEGORY.CHEATING,
  REPORT_CATEGORY.OTHER,
]
