export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  WELCOME: '/welcome',
  JOIN: '/join',
  DASHBOARD: '/dashboard',
  PATH_SELECTION: '/path-selection',
  SUBJECTS: '/subjects',
  MEMBERS: '/members',
  QUESTION_BANKS: '/question-banks',
  EXAMS: '/exams',
  EXAM_CREATE: '/exams/new',
  EXAM_EDIT: '/exams/:id/edit',
  SETTINGS: '/settings',
  SETTINGS_CHANGE_PASSWORD: '/settings/change-password',
  SETTINGS_CREATE_WORKSPACE: '/settings/create-workspace',

  REGISTER: '/register',
  REGISTER_SELECT_ROLE: '/register/select-role',
  REGISTER_DETAILS: '/register/details',
  REGISTER_PASSWORD: '/register/password',
  REGISTER_OTP: '/register/otp',
  REGISTER_SUCCESS: '/register/success',

  FORGOT_PASSWORD: '/forgot-password',
  FORGOT_PASSWORD_OTP: '/forgot-password/otp',
  RESET_PASSWORD: '/reset-password',
  RESET_PASSWORD_SUCCESS: '/reset-password/success',

  STUDENT_REGISTER: '/student/register',
  STUDENT_JOIN_CODE: '/student/join-code',
  STUDENT_DASHBOARD: '/student/dashboard',
  STUDENT_EXAMS: '/student/exams',
  STUDENT_RESULTS: '/student/results',
  STUDENT_SETTINGS: '/student/settings',

  INVITE_PREVIEW: '/invites/:token',
  INVITE_REGISTER: '/invites/:token/register',
  INVITE_ACCEPT: '/invites/:token/accept',
}
